name: nats_message_processor_client
description: Client for nats message processor

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  code_editor: ^1.0.1
  http: ^0.12.2
  mobx: 1.2.1+4
  flutter_mobx: 1.1.0+2
  rxdart: 0.25.0
  bot_toast: 3.0.5
  modal_progress_hud: 0.1.3
  google_fonts: 1.1.1
  font_awesome_flutter: 8.11.0
  web_socket_channel: 1.1.0
  uuid: ^2.2.2
  graphview: ^0.6.5
  intl: ^0.16.1

dev_dependencies:
  build_runner: 1.10.11
  mobx_codegen: 1.1.2

flutter:
  uses-material-design: true
