version: "3.5"

services:
  postgres:
    image: postgres:13.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nats:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    networks: [ "nats" ]

volumes:
  postgres_data:

networks:
  nats:
    name: nats