version: "3.5"

services:
  cassandra-seed:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - "cassandra_data_seed:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
  #    restart: always

  #  cassandra1:
  #    image: cassandra:latest
  #    volumes:
  #      - "cassandra_data_1:/var/lib/cassandra"
  #    environment:
  #      - "CASSANDRA_SEEDS=cassandra-seed"
  #      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
  #      #      needed for setting up custom cluster name
  #      - "CASSANDRA_DC=se1"
  #      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
  #    depends_on:
  #      - cassandra-seed
  #  #    restart: always
  #
  #  cassandra2:
  #    image: cassandra:latest
  #    volumes:
  #      - "cassandra_data_2:/var/lib/cassandra"
  #    environment:
  #      - "CASSANDRA_SEEDS=cassandra-seed"
  #      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
  #      #      needed for setting up custom cluster name
  #      - "CASSANDRA_DC=se1"
  #      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
  #    depends_on:
  #      - cassandra-seed
  #  #    restart: always

  nats:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    networks: [ "br.com.diego.processor.nats" ]
#  br.com.diego.processor.nats-1:
#    image: br.com.diego.processor.nats
#    command: "--cluster br.com.diego.processor.nats://0.0.0.0:6222 --routes=br.com.diego.processor.nats://ruser:T0pS3cr3t@br.com.diego.processor.nats:6222"
#    networks: [ "br.com.diego.processor.nats" ]
#    depends_on: [ "br.com.diego.processor.nats" ]
#  br.com.diego.processor.nats-2:
#    image: br.com.diego.processor.nats
#    command: "--cluster br.com.diego.processor.nats://0.0.0.0:6222 --routes=br.com.diego.processor.nats://ruser:T0pS3cr3t@br.com.diego.processor.nats:6222"
#    networks: [ "br.com.diego.processor.nats" ]
#    depends_on: [ "br.com.diego.processor.nats" ]

volumes:
  cassandra_data_seed:
  cassandra_data_1:
  cassandra_data_2:

networks:
  nats:
    name: br.com.diego.processor.nats